services:
    # Database
    db:
      image: postgres
      restart: always
      volumes:
        - .docker/db/data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: secret
    php:
        build: .docker/php
        volumes:
            - ./:/var/www/html
        restart: always

    web:
      image: nginx
      ports:
        - 443:443
        - 80:80
      volumes:
        - ./:/var/www/html
        - .docker/nginx/conf.d:/etc/nginx/conf.d
        - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - .docker/nginx/sites:/etc/nginx/sites
        - .docker/nginx/certs:/etc/nginx/certs
        - .docker/nginx/logs:/var/log/nginx
