services:
    # Database
    db:
      image: postgres
      restart: always
      volumes:
        - .docker/db/data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: secret
    php:
        build: .docker/php
        volumes:
            - ./:/var/www/html
        restart: always

    web:
      image: nginx
      ports:
        - 443:443
        - 80:80
      volumes:
        - ./:/var/www/html
        - .docker/nginx/conf.d:/etc/nginx/conf.d
        - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - .docker/nginx/sites:/etc/nginx/sites
        - .docker/nginx/certs:/etc/nginx/certs
        - .docker/nginx/logs:/var/log/nginx

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
